// Auto-generated by scripts/generate-version.mjs
export const VERSION = '0.0.0';
export const BUILD_TIME = '2025-09-19T16:56:38.245Z';
export const COMMIT_SHA = '04ca9bddbb367528456cb0d39cdcd7e63394fb2a';
export const COMMIT_SHA_SHORT = '04ca9bd';
