// Auto-generated by scripts/generate-version.mjs
export const VERSION = '0.0.0';
export const BUILD_TIME = '2025-09-19T16:51:41.084Z';
export const COMMIT_SHA = '671df01995109cac32b568b0fedd8c3e3dec3e60';
export const COMMIT_SHA_SHORT = '671df01';
